// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALJxN7oeLRnsJRpCNJUC6s7hPzrzSiP24',
    appId: '1:794199271182:web:78cda84dbedad1ebb6995f',
    messagingSenderId: '794199271182',
    projectId: 'turntimer-9612c',
    authDomain: 'turntimer-9612c.firebaseapp.com',
    databaseURL: 'https://turntimer-9612c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'turntimer-9612c.appspot.com',
    measurementId: 'G-Y9STGC8X9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4qxmnu5e4T5FNdaKhZdENqAl05Nby9os',
    appId: '1:794199271182:android:08d5304f99d6b497b6995f',
    messagingSenderId: '794199271182',
    projectId: 'turntimer-9612c',
    databaseURL: 'https://turntimer-9612c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'turntimer-9612c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjE3Thlp1FBazx8oQpiPmxutZsrtJNAOM',
    appId: '1:794199271182:ios:f13a3b7848eb145cb6995f',
    messagingSenderId: '794199271182',
    projectId: 'turntimer-9612c',
    databaseURL: 'https://turntimer-9612c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'turntimer-9612c.appspot.com',
    iosBundleId: 'com.turnTimer.vscode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjE3Thlp1FBazx8oQpiPmxutZsrtJNAOM',
    appId: '1:794199271182:ios:f13a3b7848eb145cb6995f',
    messagingSenderId: '794199271182',
    projectId: 'turntimer-9612c',
    databaseURL: 'https://turntimer-9612c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'turntimer-9612c.appspot.com',
    iosBundleId: 'com.turnTimer.vscode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALJxN7oeLRnsJRpCNJUC6s7hPzrzSiP24',
    appId: '1:794199271182:web:3e67c12f36bf4795b6995f',
    messagingSenderId: '794199271182',
    projectId: 'turntimer-9612c',
    authDomain: 'turntimer-9612c.firebaseapp.com',
    databaseURL: 'https://turntimer-9612c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'turntimer-9612c.appspot.com',
    measurementId: 'G-D9RWS1KVZV',
  );
}
